/** Todas as ações que o OpenClaw / robô do site executam de verdade. */
export const OPENCLAW_CANONICAL_ACTIONS = [
  'ping',
  'send_text_whatsapp',
  'resolve_user',
  'list_roles',
  'get_permissions',
  'check_permission',
  'list_access_requests',
  'approve_access_request',
  'reject_access_request',
  'list_categories',
  'list_contas',
  'get_saldo',
  'create_conta',
  'update_conta',
  'delete_conta',
  'list_transactions',
  'create_transaction',
  'update_transaction',
  'delete_transaction',
  'list_calendar_events',
  'list_agenda_checklist_today',
  'complete_calendar_event',
  'list_upcoming_calendar_events',
  'get_next_calendar_event',
  'create_calendar_event',
  'add_calendar_event_meet',
  'delete_calendar_event',
  'get_google_calendar_status',
  'get_nfse_setup_status',
  'sync_nfse_emitente',
  'list_nfse_clientes',
  'register_nfse_cliente',
  'list_nfse_produtos',
  'list_catalog_servicos',
  'register_nfse_produto',
  'preview_nfse',
  'emit_nfse',
  'list_nfse_notas',
  'consult_nfse',
  'get_nfse_pdf',
  'send_nfse_whatsapp',
  'list_nfe_produtos',
  'list_nfe_clientes',
  'list_nfe_catalogo',
  'register_nfe_cliente',
  'register_nfe_produto',
  'preview_nfe',
  'emit_nfe',
  'get_nfe_pdf',
  'send_nfe_whatsapp',
  'get_das_payment_status',
  'get_das_current',
  'send_das_whatsapp',
  'refresh_das_pdf',
];

/** O backend envia a resposta; ping é só diagnóstico. */
export const OPENCLAW_INTERNAL_ACTIONS = ['ping', 'send_text_whatsapp'];

export const WHATSAPP_BACKEND_AGENT_ACTIONS = OPENCLAW_CANONICAL_ACTIONS.filter(
  (action) => !OPENCLAW_INTERNAL_ACTIONS.includes(action),
);
